// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/admin_user/admin_user.proto

package admin_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AdminUser service

func NewAdminUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AdminUser service

type AdminUserService interface {
	AdminUserLogin(ctx context.Context, in *AdminUserRequest, opts ...client.CallOption) (*AdminUserResponse, error)
}

type adminUserService struct {
	c    client.Client
	name string
}

func NewAdminUserService(name string, c client.Client) AdminUserService {
	return &adminUserService{
		c:    c,
		name: name,
	}
}

func (c *adminUserService) AdminUserLogin(ctx context.Context, in *AdminUserRequest, opts ...client.CallOption) (*AdminUserResponse, error) {
	req := c.c.NewRequest(c.name, "AdminUser.AdminUserLogin", in)
	out := new(AdminUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminUser service

type AdminUserHandler interface {
	AdminUserLogin(context.Context, *AdminUserRequest, *AdminUserResponse) error
}

func RegisterAdminUserHandler(s server.Server, hdlr AdminUserHandler, opts ...server.HandlerOption) error {
	type adminUser interface {
		AdminUserLogin(ctx context.Context, in *AdminUserRequest, out *AdminUserResponse) error
	}
	type AdminUser struct {
		adminUser
	}
	h := &adminUserHandler{hdlr}
	return s.Handle(s.NewHandler(&AdminUser{h}, opts...))
}

type adminUserHandler struct {
	AdminUserHandler
}

func (h *adminUserHandler) AdminUserLogin(ctx context.Context, in *AdminUserRequest, out *AdminUserResponse) error {
	return h.AdminUserHandler.AdminUserLogin(ctx, in, out)
}
